# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170918_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('INR', 'Indian')], default='USD', max_length=1)),
            ],
        ),
    ]
