# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar'), ('INR', 'Indian Rupee')], default='USD', max_length=10),
        ),
    ]
